al_schedule:
  al_iter: 3
  num_al_incr: 50
  num_train_init: 50
net_config:
  center_at_target: true
  divergence_scale: 1.0
  layer_sizes:
  - 50
  - 50
  learning_rate: 0.0001
  ncp_scale: 0.1
  noise_std: 0.1
  ood_std_prior: null
parms:
  n_mc_samples: 100
  name_model: bnn
  sample_policy: gpa
  sampling_batch_size: 10
seed: 0
train_schedule:
  batch_size: 16
  eval_after_epochs: 10
  log_after_epochs: 300
  num_epochs: 300
